#!/bin/bash

if [ "$0" == "bash" ]; then
    echo "downloading mysetup.yml"
    git clone https://github.com/scottidler/mysetup
    exec mysetup/install
fi

sudo ansible-playbook -c local mysetup.yml
