#!/bin/bash

VERBOSE=false
declare -a SECTIONS=()
CFG="manifest.cfg"

for item in "$@"; do
    case $item in
        -v|--verbose)
            VERBOSE=true
        ;;
        *)
            SECTIONS+=("$item")
        ;;
    esac
done

function parse() {

    local cfg=$1; shift
    mkdir -p "/tmp/$cfg"
    local manifest=`mktemp -d -p "/tmp/$cfg"`

    while IFS=$'\n' read line; do
        local line="${line//[[:space:]]/}"
        if [ -n "$line" ]; then
            if [[ $line == \[*] ]]; then
                IFS="[]"
                set $line
                local section=$2
                unset var
                unset val
                mkdir $manifest/$section
                continue
            elif [[ "$line" =~ "=" ]]; then
                IFS="="
                set $line
                local var=$1
                local val=$2
            else
                local val=$line
            fi
            if [ -n "$val" ] && [ -n "$var" ]; then
                echo "$val" >> $manifest/$section/$var
            fi
        fi
    done < $cfg

    RETVAL=$manifest
}

parse $CFG
config=$RETVAL

if [ ${#SECTIONS[@]} -eq 0 ]; then
    while IFS=$'\n' read -r -d '' section; do
        if [ "$section" != "$config" ]; then
            SECTIONS+=(`basename $section`)
        fi
    done < <(find $config -maxdepth 1 -type d -print0)
fi

for section in "${SECTIONS[@]}"; do
    while IFS=$'\n' read -r -d '' key; do
        echo "key=`basename $key`"
    done < <(find "$config/$section" -maxdepth 1 -type f -print0)
done



